@host = 127.0.0.1:8000
### Get JWT Token
# @name login
POST http://{{host}}/api/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}
### Create Product
POST http://{{host}}/products/create_product/
Authorization: Bearer {{login.response.body.access}}
Content-Type: multipart/form-data; boundary=product-boundary

--product-boundary
Content-Disposition: form-data; name="name"

Acer Nitro V Laptop
--product-boundary
Content-Disposition: form-data; name="description"

Gaming laptop
--product-boundary
Content-Disposition: form-data; name="price"

1000.00
--product-boundary
Content-Disposition: form-data; name="image"; filename="AcerNV.jpg"
Content-Type: image/jpeg

< Images/AcerNV.jpg
--product-boundary--


### List all Products
GET http://{{host}}/products/get_products/
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json

### List Prodcut by ID
GET http://{{host}}/products/get_products/3
Authorization: Bearer {{login.response.body.access}}

### Delete Product
DELETE http://{{host}}/products/delete/6/
Authorization: Bearer {{login.response.body.access}}


###Update Product
PATCH http://{{host}}/products/update/7/
Authorization: Bearer {{login.response.body.access}}
Content-Type: multipart/form-data; boundary=UpdatePrdct
--UpdatePrdct
Content-Disposition: form-data; name="name"

Acer Nitro V15
--UpdatePrdct
Content-Disposition: form-data; name="price"

1500
--UpdatePrdct--



