# Generated by Django 5.2.3 on 2025-06-18 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0003_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Order_id')),
                ('order_date', models.DateField(auto_now=True)),
                ('totalAmount', models.PositiveIntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related_User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Baseapp.order')),
                ('prodcut_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baseapp.product')),
            ],
        ),
    ]
