# Generated by Django 5.2.3 on 2025-06-27 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0004_order_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Order_item',
            new_name='Cart_item',
        ),
    ]
