# Generated by Django 5.2.3 on 2025-08-06 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baseapp', '0005_rename_order_cart_rename_order_item_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='order_instance',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart_instance',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Baseapp.cart'),
            preserve_default=False,
        ),
    ]
